### ISSUE TITLE
Tags for blog posts

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy.github.io#14]
Tags will help a lot the browsing on the posts.  Some solutions are shown [in Stackoverflow](http://stackoverflow.com/questions/1408824/an-easy-way-to-support-tags-in-a-jekyll-blog).  Note that [Jekyll plugins](http://jekyllrb.com/docs/plugins/) are not a solution if we use github build system.

**Comment by nabobalis** [comment]
Added to new blog.
