### ISSUE TITLE
Add a section in About listing projects which are using sunpy

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy.github.io#16]
Currently should include Helioviewer and http://einstein.physics.drexel.edu/~solarweather/m_index.html
Anyone know of others?

**Comment by nabobalis** [comment]
Do we know any?

**Comment by nabobalis** [comment]
Ping @Cadair @dpshelio

**Comment by nabobalis** [comment]
No one seems to know. So until I get told, I'll close this.
