### ISSUE TITLE
Add more information about what features are needed for contributing code section

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy.github.io#44]

**Comment by dpshelio** [comment]
Something like [what GDL provides](http://aramis.obspm.fr/~coulais/IDL_et_GDL/Matrice_IDLvsGDL.html), though GDL has a more easier purpose in the sense they try to map 1to1 to IDL while we are not doing so with SolarSoft.

**Comment by nabobalis** [comment]
Already done by #45
