### ISSUE TITLE
Comments system for the blog

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy.github.io#7]
In the original site the comments were handled by the wordpress site.  Now, using a static site we have to take a different approach.  I would suggest disquss, but other systems are valid too.  They are easily implemented into jekyll sites.

However, I don't know whether we could import the old comments in the old posts (maybe through copy paste under the blog posts).

**Comment by nabobalis** [comment]
Do we even want comments?

**Comment by Cadair** [comment]
Yeah I am not sure comments will add a lot.

**Comment by dpshelio** [comment]
I think comments are an easy way to interact with the community. So I would vote to have them. Probably disquss is the easier and portable (in case we want to change the website).

**Comment by nabobalis** [comment]
Done for new site.
