### ISSUE TITLE
Add numfocus logo to website

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy.github.io#86]
[Now](https://www.numfocus.org/blog/numfocus-welcomes-sunpy-our-newest-fiscally-sponsored-project/) that we are sponsored by NumFOCUS we can add the logo (and the donate button) to the website.
As for example like [astropy](http://www.astropy.org/about.html), [quantecon](https://quantecon.org/) or [fenicsproject](https://fenicsproject.org/)

**Comment by nabobalis** [comment]
Added.
