### ISSUE TITLE
Remove reference/comparisons to IDL

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy.github.io#94]
This is mostly on the About page.

**Comment by ehsteve** [comment]
ping @Cadair @wafels

**Comment by nabobalis** [comment]
Approve. Any comparison to Solarsoft is a bad idea.

**Comment by Cadair** [comment]
do not speak it's name.

**Comment by dpshelio** [comment]
I agree to remove it from the about page... but maybe we need a more thoughtful guide, maybe as a different repository to show how things were done using the unnamed and how it's done now.

**Comment by Cadair** [comment]
@dpshelio if someone / some people with sufficient knowledge if both wish to do that I would be very happy to read it. Might be best in the docs of the package though.

**Comment by nabobalis** [comment]
Done for new website
